### ISSUE TITLE
API Method for getting current Instancename

### ISSUE THREAD

**Issue by Dreamtrailtv** [TimoCloud/TimoCloud#136]
**What do you have an idea for?**
TimoCloud-API

**Describe your idea**
An API Method for getting the current Instancename, e.g. Core, Proxyname or Servername

**Additional context**
Idea of a Discord member

**Comment by TimoZikeli** [comment]
You can do this e.g. with `TimoCloudAPI.getBungeeAPI().getThisProxy()`. If, for some reason, you don‘t know if you‘re on a Bungee/Bukkit/Cord system, you could use `if (TimoCloudAPI.getUniversalAPI() instanceof TimoCloudBungeeAPI)` or similar. This might not be completely clean, but what would be the use case? Otherwise, one could add an API enum type CORE/BUNGEE/… which is returned by the UniversalAPI.
